name: 'PR-Rules-Checker'
description: 'Automate PR checks with AI: validate against markdown rules and get instant feedback.'
author: 'Pablo Schaffner <pablo@puntorigen.com>'
inputs:
  github-token:
    description: 'GitHub Token to authenticate the action.'
    required: true
    default: ${{ github.token }}
  openai-api-key:
    description: 'OpenAI API Key to use the GPT-4 model.'
    required: true
  file-path:
    description: 'Path to the markdown rules file.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.openai-api-key }}
    - ${{ inputs.file-path }}
branding:
  icon: 'git-pull-request'
  color: 'blue'
