version: '3.8'

services:
  pr-rules-check:
    build: .
    container_name: pr-rules-check
    environment:
      - GITHUB_TOKEN
      - OPENAI_API_KEY
      - GITHUB_REPOSITORY
      - GITHUB_REF
      - GITHUB_SHA
      - FILE_PATH
    volumes:
      - .:/code
    entrypoint: ["python", "/pr_rules_check.py"]
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false