name: PR Rules Check (OpenAI)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr-rules-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Conditionally run this step only if it's a push to the defined branch
      - name: Run PR Rules Check for PR Events
        if: github.event_name == 'pull_request'
        uses: ./  # Use the current repository as the action source
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          file-path: '.rules/pr-rules.md'
