name: PR Rules Check (Ollama)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ollama
  issue_comment:
    types: [created, edited]
    branches:
      - ollama

env:
  BRANCH_NAME: "ollama"

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr-rules-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print event.json
        run: cat $GITHUB_EVENT_PATH
        
      # For detecting PR branch specific comments, we need to fetch the PR details first
      - name: Fetch Pull Request Details
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-rules')
        run: |
          # Extract PR number from issue_url
          PR_URL="${{ github.event.comment.issue_url }}"
          PR_NUMBER="${PR_URL##*/}"
          echo "Pull Request Number: $PR_NUMBER"
          # Fetch PR details and write base_ref to the environment file
          PR_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          BASE_REF=$(echo "$PR_DETAILS" | jq --raw-output '.base.ref')
          echo "base_ref=$BASE_REF" >> $GITHUB_ENV

      # Conditionally run this step only if it's a push to ollama branch or a PR targeting ollama branch
      - name: Run PR Rules Check for PR Events
        if: github.event_name == 'pull_request' && contains(github.ref, env.BRANCH_NAME)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: '.rules/pr-rules-ollama.md'
      
      # Conditionally run this step only if it's a comment containing '@pr-rules' in the body on a PR targeting ollama branch
      - name: Run PR Rules Check for Comment Events
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-rules') && env.base_ref == env.BRANCH_NAME
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: '.rules/pr-rules-ollama.md'
