name: PR Rules Check (Ollama)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ollama
  issue_comment:
    types: [created, edited]
    branches:
      - ollama

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr-rules-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Conditionally run this step only if it's a push to the defined branch
      - name: Run PR Rules Check for PR Events
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: '.rules/pr-rules-ollama.md'
      
      # Conditionally run this step only if it's a comment containing '@pr-rules' in the body of the PR
      - name: Run PR Rules Check for Comment Events
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-rules')
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: '.rules/pr-rules-ollama.md'
