name: PR Rules Check (Ollama)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write
  pull-requests: write
  contents: read
  
jobs:
  pr-rules-check:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'ollama')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PR Rules Check
        uses: ./  # Use the current repository as the action source
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: '.rules/pr-rules.md'
