name: PR Rules Check (OpenAI)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - openai
  issue_comment:
    types: [created, edited]
    branches:
      - openai
      
env:
  BRANCH_NAME: "openai"

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr-rules-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # For detecting PR branch specific comments, we need to fetch the PR details first
      - name: Fetch Pull Request Details
        if: github.event_name == 'issue_comment'
        id: get-pr
        run: |
          PR_NUMBER=$(echo "$GITHUB_EVENT_PATH" | jq --raw-output .issue.pull_request.number)
          PR_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          BASE_REF=$(echo "$PR_DETAILS" | jq --raw-output .base.ref)
          echo "::set-output name=base_ref::$BASE_REF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Conditionally run this step only if it's a push to defined branch or a PR targeting the defined branch
      - name: Run PR Rules Check for PR Events
        if: github.event_name == 'pull_request' && contains(github.ref, env.BRANCH_NAME)
        uses: ./  # Use the current repository as the action source
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          file-path: '.rules/pr-rules.md'

      # Conditionally run this step only if it's a comment containing '@pr-rules' in the body on a PR targeting ollama branch
      - name: Run PR Rules Check for Comment Events
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-rules') && steps.get-pr.outputs.base_ref == env.BRANCH_NAME
        uses: ./  # Use the current repository as the action source
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          file-path: '.rules/pr-rules.md'
